### ISSUE TITLE
Assignment B3 Grade

### ISSUE THREAD

**Issue by jacquelineb174** [stat545ubc-2023/assignment-b3-jacquelineb174#1]
@eemilybrown1 Hi Emily! I was hoping you could follow up with me on the reason I had five points taken off for a lack of variety in my features. I went to office hours with both Asfar and Erick, and I actually also discussed my features with Lucy when I was struggling to get the output table. Everyone told me that there was enough variation within my features and that having a layout, input buttons, as well as an output table counted as three separate features. I was even told that having three separate types of interactive buttons in my code was enough to count for three separate features that were distinct enough. Thanks in advance!

**Comment by eemilybrown1** [comment]
Hi Jacqueline! I just took another look at your assignment and I had missed the comments that you had added to the code outlining the features you added. I thought that your 3 features were the slider input, radio buttons, and select input for mass/species/sex, which is what I had considered "not enough variety". Looking back at your features, you are definitely correct that you covered enough variety. Sorry about that! I'll change your mark now.
